import tkinter as tk
from tkinter import ttk, messagebox
import numpy as np
import scipy.io as sio
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg


# ============================================================
# ADAPTIVE SONAR - PHASE 1 PYTHON DASHBOARD
# Reads results generated by MATLAB
# ============================================================

MAT_FILE = r"C:\Users\Easha\OneDrive\Documents\MATLAB\AdaptiveSonarResults\phase1_results.mat"


# ============================================================
# LOAD MATLAB DATA
# ============================================================

def load_results():

    try:
        data = sio.loadmat(MAT_FILE, squeeze_me=True,
                           struct_as_record=False)

        return data

    except Exception as e:

        messagebox.showerror(
            "MATLAB Data Error",
            "Could not load phase1_results.mat\n\n" + str(e)
        )

        return None


# ============================================================
# MATLAB STRUCT HELPER
# ============================================================

def get_struct_value(structure, name, default="N/A"):

    try:

        value = getattr(structure, name)

        if isinstance(value, np.ndarray) and value.size == 1:
            value = value.item()

        return value

    except:

        return default


# ============================================================
# CREATE DASHBOARD
# ============================================================

class SonarDashboard:

    def __init__(self, root):

        self.root = root

        self.root.title("Adaptive Sonar - Phase 1 Dashboard")

        self.root.geometry("1500x900")

        self.root.configure(bg="#111111")


        # ----------------------------------------------------
        # TITLE
        # ----------------------------------------------------

        title = tk.Label(
            root,
            text="ADAPTIVE SONAR - PHASE 1",
            font=("Arial", 24, "bold"),
            fg="white",
            bg="#111111"
        )

        title.pack(pady=10)


        subtitle = tk.Label(
            root,
            text="MATLAB Signal Engine  →  Python Visualization Dashboard",
            font=("Arial", 11),
            fg="#bbbbbb",
            bg="#111111"
        )

        subtitle.pack()


        # ----------------------------------------------------
        # MAIN FRAME
        # ----------------------------------------------------

        main_frame = tk.Frame(
            root,
            bg="#111111"
        )

        main_frame.pack(
            fill=tk.BOTH,
            expand=True,
            padx=15,
            pady=10
        )


        # ====================================================
        # LEFT INFORMATION PANEL
        # ====================================================

        left_frame = tk.Frame(
            main_frame,
            bg="#1c1c1c",
            width=300
        )

        left_frame.pack(
            side=tk.LEFT,
            fill=tk.Y,
            padx=(0, 10)
        )

        left_frame.pack_propagate(False)


        # ----------------------------------------------------
        # ENVIRONMENT
        # ----------------------------------------------------

        self.create_section(
            left_frame,
            "ENVIRONMENT"
        )

        self.depth_label = self.create_value(
            left_frame,
            "Depth"
        )

        self.turbidity_label = self.create_value(
            left_frame,
            "Turbidity"
        )

        self.temperature_label = self.create_value(
            left_frame,
            "Temperature"
        )

        self.salinity_label = self.create_value(
            left_frame,
            "Salinity"
        )


        # ----------------------------------------------------
        # CLASSIFICATION
        # ----------------------------------------------------

        self.create_section(
            left_frame,
            "CLASSIFICATION"
        )

        self.depth_state_label = self.create_value(
            left_frame,
            "Depth State"
        )

        self.turbidity_state_label = self.create_value(
            left_frame,
            "Turbidity State"
        )


        # ----------------------------------------------------
        # ADAPTIVE PARAMETERS
        # ----------------------------------------------------

        self.create_section(
            left_frame,
            "ADAPTIVE PARAMETERS"
        )

        self.start_freq_label = self.create_value(
            left_frame,
            "Start Frequency"
        )

        self.end_freq_label = self.create_value(
            left_frame,
            "End Frequency"
        )

        self.duration_label = self.create_value(
            left_frame,
            "Pulse Duration"
        )

        self.amplitude_label = self.create_value(
            left_frame,
            "Amplitude"
        )

        self.waveform_label = self.create_value(
            left_frame,
            "Waveform"
        )


        # ----------------------------------------------------
        # SIGNAL INFORMATION
        # ----------------------------------------------------

        self.create_section(
            left_frame,
            "SIGNAL OUTPUT"
        )

        self.samples_label = self.create_value(
            left_frame,
            "Samples"
        )

        self.sampling_label = self.create_value(
            left_frame,
            "Sampling Rate"
        )

        self.peak_label = self.create_value(
            left_frame,
            "Peak Amplitude"
        )


        # ----------------------------------------------------
        # REFRESH BUTTON
        # ----------------------------------------------------

        refresh_button = tk.Button(
            left_frame,
            text="REFRESH FROM MATLAB",
            command=self.update_dashboard,
            font=("Arial", 11, "bold"),
            bg="#333333",
            fg="white",
            padx=10,
            pady=8
        )

        refresh_button.pack(
            pady=25
        )


        # ====================================================
        # RIGHT GRAPH AREA
        # ====================================================

        right_frame = tk.Frame(
            main_frame,
            bg="#111111"
        )

        right_frame.pack(
            side=tk.RIGHT,
            fill=tk.BOTH,
            expand=True
        )


        # ----------------------------------------------------
        # MATPLOTLIB FIGURE
        # ----------------------------------------------------

        self.figure, self.axes = plt.subplots(
            2,
            2,
            figsize=(10, 7)
        )

        self.figure.patch.set_facecolor("#111111")


        for ax in self.axes.flat:

            ax.set_facecolor("#181818")

            ax.tick_params(
                colors="white"
            )

            ax.xaxis.label.set_color("white")

            ax.yaxis.label.set_color("white")

            ax.title.set_color("white")

            for spine in ax.spines.values():

                spine.set_color("#777777")


            ax.grid(
                True,
                alpha=0.2
            )


        self.figure.tight_layout(
            pad=3
        )


        self.canvas = FigureCanvasTkAgg(
            self.figure,
            master=right_frame
        )

        self.canvas.get_tk_widget().pack(
            fill=tk.BOTH,
            expand=True
        )


        # ----------------------------------------------------
        # INITIAL LOAD
        # ----------------------------------------------------

        self.update_dashboard()


    # ========================================================
    # UI HELPERS
    # ========================================================

    def create_section(self, parent, text):

        label = tk.Label(
            parent,
            text=text,
            font=("Arial", 12, "bold"),
            fg="#00d9ff",
            bg="#1c1c1c",
            anchor="w"
        )

        label.pack(
            fill=tk.X,
            padx=15,
            pady=(18, 7)
        )


    def create_value(self, parent, name):

        frame = tk.Frame(
            parent,
            bg="#1c1c1c"
        )

        frame.pack(
            fill=tk.X,
            padx=15,
            pady=3
        )


        name_label = tk.Label(
            frame,
            text=name,
            font=("Arial", 10),
            fg="#bbbbbb",
            bg="#1c1c1c",
            anchor="w"
        )

        name_label.pack(
            side=tk.LEFT
        )


        value_label = tk.Label(
            frame,
            text="--",
            font=("Arial", 10, "bold"),
            fg="white",
            bg="#1c1c1c",
            anchor="e"
        )

        value_label.pack(
            side=tk.RIGHT
        )


        return value_label


    # ========================================================
    # UPDATE DASHBOARD
    # ========================================================

    def update_dashboard(self):

        data = load_results()

        if data is None:
            return


        # ----------------------------------------------------
        # MATLAB STRUCTURES
        # ----------------------------------------------------

        env = data.get("env", None)

        params = data.get("params", None)


        # ----------------------------------------------------
        # ENVIRONMENT
        # ----------------------------------------------------

        if env is not None:

            depth = get_struct_value(
                env,
                "depth"
            )

            turbidity = get_struct_value(
                env,
                "turbidity"
            )

            temperature = get_struct_value(
                env,
                "temperature"
            )

            salinity = get_struct_value(
                env,
                "salinity"
            )

            depth_state = get_struct_value(
                env,
                "depth_state"
            )

            turbidity_state = get_struct_value(
                env,
                "turbidity_state"
            )


            self.depth_label.config(
                text="%.1f m" % depth
            )

            self.turbidity_label.config(
                text="%.1f %%" % turbidity
            )

            self.temperature_label.config(
                text="%.1f C" % temperature
            )

            self.salinity_label.config(
                text="%.1f PSU" % salinity
            )

            self.depth_state_label.config(
                text=str(depth_state)
            )

            self.turbidity_state_label.config(
                text=str(turbidity_state)
            )


        # ----------------------------------------------------
        # ADAPTIVE PARAMETERS
        # ----------------------------------------------------

        if params is not None:

            f_start = get_struct_value(
                params,
                "f_start"
            )

            f_end = get_struct_value(
                params,
                "f_end"
            )

            duration = get_struct_value(
                params,
                "pulse_duration"
            )

            amplitude = get_struct_value(
                params,
                "amplitude"
            )

            waveform = get_struct_value(
                params,
                "waveform"
            )


            self.start_freq_label.config(
                text="%.1f kHz" % (f_start / 1000)
            )

            self.end_freq_label.config(
                text="%.1f kHz" % (f_end / 1000)
            )

            self.duration_label.config(
                text="%.2f ms" % (duration * 1000)
            )

            self.amplitude_label.config(
                text="%.2f" % amplitude
            )

            self.waveform_label.config(
                text=str(waveform)
            )


        # ----------------------------------------------------
        # SIGNAL
        # ----------------------------------------------------

        signal = np.asarray(
            data.get("signal", [])
        ).flatten()


        t = np.asarray(
            data.get("t", [])
        ).flatten()


        inst_freq = np.asarray(
            data.get("inst_freq", [])
        ).flatten()


        fs = data.get(
            "fs",
            5e6
        )


        if np.size(fs) == 1:

            fs = float(np.asarray(fs).flatten()[0])


        # ----------------------------------------------------
        # SIGNAL INFORMATION
        # ----------------------------------------------------

        self.samples_label.config(
            text=str(len(signal))
        )

        self.sampling_label.config(
            text="%.1f MHz" % (fs / 1e6)
        )


        if len(signal) > 0:

            self.peak_label.config(
                text="%.3f" % np.max(np.abs(signal))
            )


        # ====================================================
        # GRAPHS
        # ====================================================

        for ax in self.axes.flat:

            ax.clear()

            ax.set_facecolor("#181818")

            ax.tick_params(
                colors="white"
            )

            ax.xaxis.label.set_color("white")

            ax.yaxis.label.set_color("white")

            ax.title.set_color("white")

            for spine in ax.spines.values():

                spine.set_color("#777777")

            ax.grid(
                True,
                alpha=0.2
            )


        # ----------------------------------------------------
        # WAVEFORM
        # ----------------------------------------------------

        if len(signal) > 0 and len(t) > 0:

            self.axes[0, 0].plot(
                t * 1000,
                signal
            )

        self.axes[0, 0].set_title(
            "Sonar Waveform"
        )

        self.axes[0, 0].set_xlabel(
            "Time (ms)"
        )

        self.axes[0, 0].set_ylabel(
            "Amplitude"
        )


        # ----------------------------------------------------
        # INSTANTANEOUS FREQUENCY
        # ----------------------------------------------------

        if len(inst_freq) > 0 and len(t) > 0:

            n = min(
                len(t),
                len(inst_freq)
            )

            self.axes[0, 1].plot(
                t[:n] * 1000,
                inst_freq[:n] / 1000
            )

        self.axes[0, 1].set_title(
            "Instantaneous Frequency"
        )

        self.axes[0, 1].set_xlabel(
            "Time (ms)"
        )

        self.axes[0, 1].set_ylabel(
            "Frequency (kHz)"
        )


        # ----------------------------------------------------
        # FREQUENCY SPECTRUM
        # ----------------------------------------------------

        f = np.asarray(
            data.get("f", [])
        ).flatten()


        magnitude = np.asarray(
            data.get("magnitude", [])
        ).flatten()


        if len(f) > 0 and len(magnitude) > 0:

            n = min(
                len(f),
                len(magnitude)
            )

            self.axes[1, 0].plot(
                f[:n] / 1000,
                magnitude[:n]
            )


        self.axes[1, 0].set_title(
            "Frequency Spectrum"
        )

        self.axes[1, 0].set_xlabel(
            "Frequency (kHz)"
        )

        self.axes[1, 0].set_ylabel(
            "Magnitude"
        )


        # ----------------------------------------------------
        # AUTOCORRELATION
        # ----------------------------------------------------

        acor = np.asarray(
            data.get("acor", [])
        ).flatten()


        lag = np.asarray(
            data.get("lag", [])
        ).flatten()


        if len(acor) > 0 and len(lag) > 0:

            n = min(
                len(acor),
                len(lag)
            )

            self.axes[1, 1].plot(
                lag[:n] / fs * 1000,
                acor[:n]
            )


        self.axes[1, 1].set_title(
            "Autocorrelation"
        )

        self.axes[1, 1].set_xlabel(
            "Lag (ms)"
        )

        self.axes[1, 1].set_ylabel(
            "Correlation"
        )


        # ----------------------------------------------------
        # REFRESH
        # ----------------------------------------------------

        self.figure.tight_layout(
            pad=3
        )

        self.canvas.draw()


# ============================================================
# START APPLICATION
# ============================================================

if __name__ == "__main__":

    root = tk.Tk()

    app = SonarDashboard(root)

    root.mainloop()