function phase1_dashboard
clc;
close all;

% ==========================================================
% ADAPTIVE SONAR - PHASE 1
% VISUAL DASHBOARD
% MATLAB 2016 COMPATIBLE
% ==========================================================

% ----------------------------------------------------------
% ENVIRONMENT INPUTS
% Change these values to test different environments
% ----------------------------------------------------------

depth       = 150;      % meters
turbidity   = 90;       % %
temperature = 20;       % Celsius
salinity    = 35;       % PSU

% Sampling frequency
fs = 5e6;

% ----------------------------------------------------------
% ENVIRONMENT MODEL
% ----------------------------------------------------------

env = environment_model(depth, turbidity, temperature, salinity);

% ----------------------------------------------------------
% ADAPTATION ENGINE
% ----------------------------------------------------------

params = adaptation(env);

% ----------------------------------------------------------
% SELECT WAVEFORM
% ----------------------------------------------------------

switch upper(params.waveform)

    case 'LFM'

        [t, signal, inst_freq] = ...
            lfm_generator(params, fs);

        waveform_name = 'LFM';

    case 'GEOMETRIC'

        [t, signal, inst_freq] = ...
            geometric_generator(params, fs);

        waveform_name = 'GEOMETRIC';

    case 'BARKER'

        [t, signal, code] = ...
            barker_generator(params, fs);

        % Barker does not have an instantaneous frequency
        inst_freq = zeros(size(t));

        waveform_name = 'BARKER';

    otherwise

        error('Unknown waveform selected.');

end

% ----------------------------------------------------------
% BASIC SIGNAL PARAMETERS
% ----------------------------------------------------------

samples = length(signal);

duration = samples/fs;

peak_amplitude = max(abs(signal));

bandwidth = params.f_end - params.f_start;

signal_energy = sum(signal.^2);

% ----------------------------------------------------------
% AUTOCORRELATION
% ----------------------------------------------------------

[acor, lag] = xcorr(signal);

lag_ms = lag/fs*1000;

% ----------------------------------------------------------
% FFT
% ----------------------------------------------------------

[f, magnitude] = fft_analysis(signal, fs);

% ----------------------------------------------------------
% CREATE DASHBOARD WINDOW
% ----------------------------------------------------------

screen_size = get(0,'ScreenSize');

fig_width  = 1200;
fig_height = 750;

fig_x = (screen_size(3)-fig_width)/2;
fig_y = (screen_size(4)-fig_height)/2;

fig = figure( ...
    'Name','Adaptive Sonar - Phase 1 Dashboard', ...
    'NumberTitle','off', ...
    'Position',[fig_x fig_y fig_width fig_height], ...
    'Color',[0.94 0.94 0.94]);

% ==========================================================
% TITLE
% ==========================================================

uicontrol( ...
    'Parent',fig, ...
    'Style','text', ...
    'String','ADAPTIVE SONAR - PHASE 1 VISUAL DASHBOARD', ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'BackgroundColor',[0.94 0.94 0.94], ...
    'Position',[250 705 700 35]);

uicontrol( ...
    'Parent',fig, ...
    'Style','text', ...
    'String','Environment Classification  ->  Adaptive Waveform Selection', ...
    'FontSize',10, ...
    'BackgroundColor',[0.94 0.94 0.94], ...
    'Position',[350 680 500 25]);

% ==========================================================
% LEFT INFORMATION PANEL
% ==========================================================

panel1 = uipanel( ...
    'Parent',fig, ...
    'Title','ENVIRONMENT', ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'Position',[0.02 0.57 0.22 0.32]);

% Environment values

uicontrol(panel1,'Style','text',...
    'String','Depth',...
    'HorizontalAlignment','left',...
    'Position',[15 125 100 25]);

uicontrol(panel1,'Style','text',...
    'String',sprintf('%.1f m',depth),...
    'FontWeight','bold',...
    'HorizontalAlignment','right',...
    'Position',[100 125 120 25]);

uicontrol(panel1,'Style','text',...
    'String','Turbidity',...
    'HorizontalAlignment','left',...
    'Position',[15 95 100 25]);

uicontrol(panel1,'Style','text',...
    'String',sprintf('%.1f %%',turbidity),...
    'FontWeight','bold',...
    'HorizontalAlignment','right',...
    'Position',[100 95 120 25]);

uicontrol(panel1,'Style','text',...
    'String','Temperature',...
    'HorizontalAlignment','left',...
    'Position',[15 65 100 25]);

uicontrol(panel1,'Style','text',...
    'String',sprintf('%.1f C',temperature),...
    'FontWeight','bold',...
    'HorizontalAlignment','right',...
    'Position',[100 65 120 25]);

uicontrol(panel1,'Style','text',...
    'String','Salinity',...
    'HorizontalAlignment','left',...
    'Position',[15 35 100 25]);

uicontrol(panel1,'Style','text',...
    'String',sprintf('%.1f PSU',salinity),...
    'FontWeight','bold',...
    'HorizontalAlignment','right',...
    'Position',[100 35 120 25]);

% ==========================================================
% CLASSIFICATION PANEL
% ==========================================================

panel2 = uipanel( ...
    'Parent',fig, ...
    'Title','CLASSIFICATION', ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'Position',[0.02 0.34 0.22 0.20]);

uicontrol(panel2,'Style','text',...
    'String','Depth State',...
    'HorizontalAlignment','left',...
    'Position',[15 75 100 25]);

uicontrol(panel2,'Style','text',...
    'String',env.depth_state,...
    'FontWeight','bold',...
    'FontSize',11,...
    'HorizontalAlignment','right',...
    'Position',[100 75 120 25]);

uicontrol(panel2,'Style','text',...
    'String','Turbidity',...
    'HorizontalAlignment','left',...
    'Position',[15 40 100 25]);

uicontrol(panel2,'Style','text',...
    'String',env.turbidity_state,...
    'FontWeight','bold',...
    'FontSize',11,...
    'HorizontalAlignment','right',...
    'Position',[100 40 120 25]);

% ==========================================================
% ADAPTIVE PARAMETERS PANEL
% ==========================================================

panel3 = uipanel( ...
    'Parent',fig, ...
    'Title','ADAPTIVE PARAMETERS', ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'Position',[0.02 0.04 0.22 0.26]);

uicontrol(panel3,'Style','text',...
    'String','Start Frequency',...
    'HorizontalAlignment','left',...
    'Position',[10 130 110 25]);

uicontrol(panel3,'Style','text',...
    'String',sprintf('%.1f kHz',params.f_start/1000),...
    'FontWeight','bold',...
    'HorizontalAlignment','right',...
    'Position',[120 130 100 25]);

uicontrol(panel3,'Style','text',...
    'String','End Frequency',...
    'HorizontalAlignment','left',...
    'Position',[10 100 110 25]);

uicontrol(panel3,'Style','text',...
    'String',sprintf('%.1f kHz',params.f_end/1000),...
    'FontWeight','bold',...
    'HorizontalAlignment','right',...
    'Position',[120 100 100 25]);

uicontrol(panel3,'Style','text',...
    'String','Pulse Duration',...
    'HorizontalAlignment','left',...
    'Position',[10 70 110 25]);

uicontrol(panel3,'Style','text',...
    'String',sprintf('%.2f ms',params.pulse_duration*1000),...
    'FontWeight','bold',...
    'HorizontalAlignment','right',...
    'Position',[120 70 100 25]);

uicontrol(panel3,'Style','text',...
    'String','Amplitude',...
    'HorizontalAlignment','left',...
    'Position',[10 40 110 25]);

uicontrol(panel3,'Style','text',...
    'String',sprintf('%.2f',params.amplitude),...
    'FontWeight','bold',...
    'HorizontalAlignment','right',...
    'Position',[120 40 100 25]);

% ==========================================================
% WAVEFORM DECISION PANEL
% ==========================================================

panel4 = uipanel( ...
    'Parent',fig, ...
    'Title','WAVEFORM DECISION', ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'Position',[0.26 0.77 0.72 0.12]);

uicontrol(panel4,'Style','text',...
    'String','SELECTED WAVEFORM',...
    'FontSize',10,...
    'Position',[30 30 180 30]);

uicontrol(panel4,'Style','text',...
    'String',waveform_name,...
    'FontSize',15,...
    'FontWeight','bold',...
    'Position',[210 25 200 40]);

uicontrol(panel4,'Style','text',...
    'String',sprintf('Bandwidth: %.1f kHz',bandwidth/1000),...
    'Position',[500 30 180 30]);

% ==========================================================
% WAVEFORM PLOT
% ==========================================================

ax1 = axes( ...
    'Parent',fig, ...
    'Position',[0.29 0.48 0.32 0.23]);

plot(ax1,t*1000,signal);

xlabel(ax1,'Time (ms)');
ylabel(ax1,'Amplitude');

title(ax1,[waveform_name ' Waveform']);

grid(ax1,'on');

% ==========================================================
% FREQUENCY / INSTANTANEOUS FREQUENCY
% ==========================================================

ax2 = axes( ...
    'Parent',fig, ...
    'Position',[0.65 0.48 0.32 0.23]);

if strcmpi(waveform_name,'BARKER')

    % Barker has no frequency sweep
    plot(ax2,t*1000,signal);

    xlabel(ax2,'Time (ms)');
    ylabel(ax2,'Amplitude');

    title(ax2,'Barker Phase Code');

else

    plot(ax2,t*1000,inst_freq/1000);

    xlabel(ax2,'Time (ms)');
    ylabel(ax2,'Frequency (kHz)');

    title(ax2,'Instantaneous Frequency');

end

grid(ax2,'on');

% ==========================================================
% FFT SPECTRUM
% ==========================================================

ax3 = axes( ...
    'Parent',fig, ...
    'Position',[0.29 0.10 0.32 0.27]);

plot(ax3,f/1000,magnitude);

xlabel(ax3,'Frequency (kHz)');
ylabel(ax3,'Magnitude');

title(ax3,'Frequency Spectrum');

grid(ax3,'on');

xlim(ax3,[0 600]);

% ==========================================================
% AUTOCORRELATION
% ==========================================================

ax4 = axes( ...
    'Parent',fig, ...
    'Position',[0.65 0.10 0.32 0.27]);

plot(ax4,lag_ms,acor);

xlabel(ax4,'Lag (ms)');
ylabel(ax4,'Correlation');

title(ax4,'Autocorrelation');

grid(ax4,'on');

% ==========================================================
% STATUS BAR
% ==========================================================

uicontrol( ...
    'Parent',fig, ...
    'Style','text', ...
    'String',sprintf( ...
    'STATUS: ADAPTATION COMPLETE   |   %s   |   %.1f-%.1f kHz   |   %.2f ms   |   %d samples', ...
    waveform_name,...
    params.f_start/1000,...
    params.f_end/1000,...
    params.pulse_duration*1000,...
    samples), ...
    'FontSize',10,...
    'FontWeight','bold',...
    'BackgroundColor',[0.94 0.94 0.94],...
    'Position',[250 20 900 30]);

% ==========================================================
% COMMAND WINDOW SUMMARY
% ==========================================================

fprintf('\n');
fprintf('====================================================\n');
fprintf('       ADAPTIVE SONAR - PHASE 1 DASHBOARD\n');
fprintf('====================================================\n');

fprintf('\nENVIRONMENT\n');
fprintf('Depth        : %.1f m\n',depth);
fprintf('Turbidity    : %.1f %%\n',turbidity);
fprintf('Temperature  : %.1f C\n',temperature);
fprintf('Salinity     : %.1f PSU\n',salinity);

fprintf('\nCLASSIFICATION\n');
fprintf('Depth State  : %s\n',env.depth_state);
fprintf('Turbidity    : %s\n',env.turbidity_state);

fprintf('\nADAPTIVE PARAMETERS\n');
fprintf('Start Freq   : %.1f kHz\n',params.f_start/1000);
fprintf('End Freq     : %.1f kHz\n',params.f_end/1000);
fprintf('Pulse        : %.2f ms\n',params.pulse_duration*1000);
fprintf('Amplitude    : %.2f\n',params.amplitude);

fprintf('\nDECISION\n');
fprintf('Selected Waveform : %s\n',waveform_name);

fprintf('\nSIGNAL OUTPUT\n');
fprintf('Samples           : %d\n',samples);
fprintf('Duration          : %.3f ms\n',duration*1000);
fprintf('Peak Amplitude    : %.3f\n',peak_amplitude);
fprintf('Bandwidth         : %.1f kHz\n',bandwidth/1000);
fprintf('Signal Energy     : %.2f\n',signal_energy);
fprintf('Sampling Rate     : %.1f MHz\n',fs/1e6);

fprintf('\n====================================================\n');
fprintf('       PHASE 1 VISUAL DASHBOARD READY\n');
fprintf('====================================================\n');

end